/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 7.0.1   2017-03-29

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32f10x.h"
#include <stdio.h>
#include "sys_usart.h"
#include "sys_timer.h"
#include "sys_init.h"
#include "mac0control.h"
#include "mac1control.h"
#include "calendar.h"
#define STM32F10X_MD_VL
/* Private typedef */
/* Private define  */
extern uint16_t set_bacnet_bin_alarm;
extern uint8_t set_bacnet_bin_alarm_active;
/* Private macro */
/* Private variables */

//uip_tcp_appstate_t data;
/* Private function prototypes */
/* Private functions */


/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main()
{
	//uint8_t mode;
	uint32_t display_timeout;
	uint32_t tcp_timeout;
	sys_init();
	printf("\n-------------------------\n");
	printf("Starting Ethernet Init \n");
	mac0_init();
	mac1_init();
	Sys_Delay(100);
	printf("Init completed\n");
	tcp_timeout = Sys_GetTick() + 8000;
	mac0_service(1,1,0);
	while(tcp_timeout>Sys_GetTick()){
		mac0_tick();
	}
	//set_date();
	//mode = 0;
	//Sys_Delay(5000);
	tcp_timeout = Sys_GetTick() + 8000;
	mac0_service(1,0,9);
	while(tcp_timeout>Sys_GetTick()){
		mac0_tick();
	}
	while(1)
	{
		//Sys_Delay(1000);
		display_timeout = Sys_GetTick();
		//printf("1 %d ",periodic_timer);

		mac0_tick();
		mac0_service(1,0,0);
		mac1_tick();

		if(set_bacnet_bin_alarm)
		{
			printf("Bacnet Alarm %d \n",set_bacnet_bin_alarm);
			mac0_service(set_bacnet_bin_alarm_active,0,set_bacnet_bin_alarm);
			set_bacnet_bin_alarm_active = 0;
		}else if(GPIO_ReadInputDataBit(GPIOA,GPIO_Pin_3))
		{
			printf("Bacnet Alarm %d \n",set_bacnet_bin_alarm);
			mac0_service(1,0,4);
		}

		mac1_service();
//		printf("-\r");
		if((display_timeout%20000) == 0){
			get_RTC();
			display_date();
			printf(" : \n");
			mac0_service(1,0,8);
		}
		//printf("\n");
		//Time_Show();


	}
}




